language: python
python:
  - "2.6"
  - "2.7"
install:
  pip install -r requirements.txt ; pip install flake8
before_script: 
  flake8 src/signalfx_metadata.py
script: 
  for x in src/*.py; do python $x once; done
