version: 2
jobs:
  build:
    working_directory: ~/signalfx/signalfx-collectd-plugin
    parallelism: 6
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      PATH: $HOME/.local/bin:/bin:$PATH
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
        command: /sbin/init
    steps:
      - type: shell
        shell: /bin/sh
        pwd: /
        command: apt-get -U add git openssh
      - type: checkout
      - type: shell
        shell: /bin/sh
        command: return 0
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - restore_cache:
          keys:
          # This branch if available
          - v1-dep-{{ .Branch }}-
          # Default branch if not
          - v1-dep-master-
          # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
          - v1-dep-
      - run: pip install pep8==1.7.0 flake8==3.3.0 nose==1.3.7 pylint==1.7.1
      - run: pip install -r requirements.txt
      - run: gem install mdl
      # Save dependency cache
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
          - vendor/bundle
          - ~/virtualenvs
          - ~/.bundle
          - ~/.local
      - run:
          name: bash verify.sh
          command: if [ "$CIRCLE_NODE_INDEX" == "0" ]; then bash verify.sh; fi
      # Save test results
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
